name: Create Pull Request

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    if: contains(github.event.head_commit.message, '#done')  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev 
          title: "Auto PR from ${{ github.ref }} to dev"
          body: "Cette PR a été créée automatiquement depuis la branche ${{ github.ref }}."
          labels: "automated-pr"
          draft: false
