name: Merge Pull Request and Delete Branch

on:
  pull_request_review:
    types: [submitted] 

jobs:
  merge_and_cleanup:
    if: github.event.review.state == 'approved' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Merge the Pull Request
        uses: peter-evans/merge-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          merge-method: squash 
          delete-branch: true  
